/* global window */
// ── Mock session for demo/fallback ──────────────────────────────────────────

const MOCK_SESSION = {
  id: "visionlab-sparse-moe-vit",
  repo: "visionlab/sparse-moe-vit",
  title: "Sparse Mixture-of-Experts Routing for Efficient Vision Transformers",
  venue: "NeurIPS 2024",
  stars: "1.4k",
  headline: "Top-1 82.7% on ImageNet-1k @ 4.1 GFLOPs",
  created_at: new Date(Date.now() - 3600000).toISOString(),
  files: {
    "Dockerfile": `FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

# system packages + python 3.10
RUN apt-get update && apt-get install -y --no-install-recommends \\
      python3.10 python3-pip git && \\
      rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
RUN git clone https://github.com/visionlab/sparse-moe-vit .

# pinned PyTorch 2.1.0+cu118 — matches paper environment
RUN pip install torch==2.1.0+cu118 \\
      --index-url https://download.pytorch.org/whl/cu118
RUN pip install torchvision==0.16.0+cu118 \\
      --index-url https://download.pytorch.org/whl/cu118
RUN pip install --no-cache-dir \\
      timm==0.9.12 \\
      einops==0.7.0 \\
      numpy==1.26.4 \\
      pyyaml==6.0.1

# determinism settings (auto-injected by repro-agent)
ENV PYTHONHASHSEED=0 \\
    CUBLAS_WORKSPACE_CONFIG=:4096:8 \\
    PYTHONDONTWRITEBYTECODE=1

ENTRYPOINT ["python3.10", "train.py"]`,

    "reproduce.sh": `#!/bin/bash
# Reproduction script for visionlab/sparse-moe-vit
# Generated by repro-agent — review REPRO_NOTES.md before running
set -euo pipefail

IMAGE="sparse-moe-vit:repro"
DATA_DIR="\${1:-/data/imagenet}"

echo "==> Building Docker image..."
docker build -t "$IMAGE" .

echo "==> Training with paper hyperparameters (seed=42, warmup=10k steps)..."
docker run --gpus all \\
  -v "$DATA_DIR:/data" \\
  -e SEED=42 \\
  "$IMAGE" \\
  train.py --config configs/vit_moe_base.yaml --seed 42 --warmup-steps 10000

echo "==> Evaluating and computing delta vs. Table 2..."
docker run --gpus all \\
  -v "$DATA_DIR:/data" \\
  -v "\$(pwd)/runs:/workspace/runs" \\
  "$IMAGE" \\
  eval.py --ckpt runs/best.pt --report`,

    "requirements-pinned.txt": `# Pinned for NeurIPS 2024 reproduction — CUDA 11.8 / PyTorch 2.1.0
# Generated by repro-agent from requirements.txt + paper §4.1
torch==2.1.0+cu118
torchvision==0.16.0+cu118
timm==0.9.12
einops==0.7.0
numpy==1.26.4
pyyaml==6.0.1`,

    "REPRO_NOTES.md": `# Reproduction Notes
## visionlab/sparse-moe-vit · NeurIPS 2024

**Claim**: Top-1 82.7% on ImageNet-1k @ 4.1 GFLOPs

---

## Environment

| Component | Version | Source |
|-----------|---------|--------|
| Python    | 3.10    | setup.py |
| CUDA      | 11.8    | inferred from paper §4 |
| PyTorch   | 2.1.0+cu118 | requirements.txt |
| GPU       | A100 80GB | paper §4.1 |

---

## Reproduction risks

### ⚠ HIGH — Random seed not fixed
\`train.py\` never calls \`torch.manual_seed\`. Results are non-deterministic.
**Fix applied**: \`--seed 42\` + \`PYTHONHASHSEED=0\` + \`CUBLAS_WORKSPACE_CONFIG\` injected.

### ⚠ HIGH — CUDA version mismatch
README install snippet pins \`cu121\` but paper reports \`cu118\` numbers.
**Fix applied**: Dockerfile uses \`cuda:11.8.0\` base.

### ◆ MEDIUM — warmup_steps unspecified
Not in config or README. Digitized from Figure 3 LR schedule.
**Fix applied**: \`--warmup-steps 10000\` added to reproduce.sh.

### ◆ MEDIUM — preprocess.sh missing
Referenced in README but absent from repo. Reconstructed from §3.2.
**Fix applied**: Standard ImageNet pipeline (224px, RandAug, ImageNet mean/std).

---

## How to run

\`\`\`bash
bash reproduce.sh /path/to/imagenet
\`\`\`

Full train ≈ 38 GPU-hours on a single A100.
`,
  },
  risks: [
    { sev: "high", name: "Random seed not fixed", desc: "train.py never calls torch.manual_seed; results are non-deterministic run-to-run.", fix: "Injected --seed 42, PYTHONHASHSEED=0, and CUBLAS_WORKSPACE_CONFIG in reproduce.sh and Dockerfile." },
    { sev: "high", name: "CUDA version mismatch", desc: "README pins cu121, but paper §4 results were produced on CUDA 11.8.", fix: "Dockerfile base pinned to cuda:11.8.0-cudnn8-devel." },
    { sev: "medium", name: "warmup_steps unspecified", desc: "LR warmup appears in Figure 3 but is absent from config.", fix: "Estimated 10k steps by digitizing the LR schedule plot." },
    { sev: "medium", name: "Preprocessing script missing", desc: "data/preprocess.sh referenced in README but not in repo.", fix: "Reconstructed from §3.2: 224px RandAug, ImageNet mean/std." },
    { sev: "low", name: "Mixed-precision default", desc: "Config defaults to fp16; paper text mentions bf16.", fix: "reproduce.sh passes --amp-dtype bf16." },
  ],
  env_spec: [
    { k: "Python", v: "3.10" },
    { k: "CUDA", v: "11.8" },
    { k: "PyTorch", v: "2.1.0+cu118" },
    { k: "GPU", v: "A100 80GB" },
    { k: "OS", v: "Ubuntu 22.04" },
  ],
};

const INITIAL_CHAT = [
  {
    who: "agent",
    text: "I analyzed <b>visionlab/sparse-moe-vit</b> and generated 4 reproduction files. There are <b>2 high-severity risks</b> — both are mitigated in the generated files. Run <code>bash reproduce.sh /data/imagenet</code> to start.",
  },
];

const SCRIPTED = {
  delta: {
    text: "Verified the reproduction run against <b>Table 2</b>. Top-1 lands within <b>0.1%</b> of the paper after pinning CUDA 11.8 and fixing the seed.",
    card: {
      head: "Delta vs. Table 2",
      rows: [
        { k: "Top-1 accuracy", a: "82.7%", b: "82.6%", d: "−0.1%", pos: true },
        { k: "GFLOPs", a: "4.1", b: "4.1", d: "0.0", pos: true },
        { k: "Params (M)", a: "29.3", b: "29.3", d: "0.0", pos: true },
      ],
    },
  },
  risk: { text: "The two high-severity risks are a missing random seed and a CUDA 11.8/12.1 mismatch. Both are fixed in the generated <code>Dockerfile</code> and <code>reproduce.sh</code>." },
  docker: { text: "The <code>Dockerfile</code> uses <code>nvidia/cuda:11.8.0-cudnn8-devel</code>, pins <code>torch==2.1.0+cu118</code>, and injects determinism env vars. Click it in the file list to copy." },
  fallback: { text: "Got it. You can edit any of the generated files directly by clicking them in the file list on the left." },
};

const SUGGESTIONS = [
  { k: "delta", label: "Verify delta vs. paper numbers" },
  { k: "risk", label: "Explain the reproduction risks" },
  { k: "docker", label: "Walk me through the Dockerfile" },
];

Object.assign(window, { MOCK_SESSION, INITIAL_CHAT, SCRIPTED, SUGGESTIONS });
